spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/blog?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
  mail:
    host: smtp.qq.com
    username: mail
    password: password
    default-encoding: UTF-8
    port: 587
    protocol: smtp
    properties:
      "mail.transport.protocol": smtp
      "mail.smtp.auth": true
      "mail.smtp.starttls.enable": true

server:
  port: 8081
  ssl:
    key-store:
    key-store-password:

# 日志配置
logging:
  level:
    com.hy: debug
    org.springframework: warn

# mybatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mybatis/mappers/**/*.xml
  type-aliases-package: com.hy.blog.entity

# mybatis插件
pagehelper:
  auto-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count-countSql